//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVBack.Crosscutting.Utils.Errors {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessagesTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessagesTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectVBack.Crosscutting.Utils.Errors.ExceptionMessagesTexts", typeof(ExceptionMessagesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You wasn&apos;t able to autheticate.
        /// </summary>
        public static string AuthenticateError {
            get {
                return ResourceManager.GetString("AuthenticateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category can&apos;t be created.
        /// </summary>
        public static string CategoryCreateError {
            get {
                return ResourceManager.GetString("CategoryCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category can&apos;t be created.
        /// </summary>
        public static string CategoryCreatingError {
            get {
                return ResourceManager.GetString("CategoryCreatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t edit a default category.
        /// </summary>
        public static string CategoryDefault {
            get {
                return ResourceManager.GetString("CategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category not found.
        /// </summary>
        public static string CategoryNotFoundError {
            get {
                return ResourceManager.GetString("CategoryNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid category.
        /// </summary>
        public static string InvalidCategoryError {
            get {
                return ResourceManager.GetString("InvalidCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid transaction.
        /// </summary>
        public static string InvalidTransactionError {
            get {
                return ResourceManager.GetString("InvalidTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid user.
        /// </summary>
        public static string InvalidUserError {
            get {
                return ResourceManager.GetString("InvalidUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction not found.
        /// </summary>
        public static string TransactionNotFoundError {
            get {
                return ResourceManager.GetString("TransactionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
    }
}
