//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVBack.Crosscutting.Utils.Errors {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessagesTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectVBack.Crosscutting.Utils.Errors.ValidationMessagesTexts", typeof(ValidationMessagesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description must have between 1 and 200 characters.
        /// </summary>
        public static string DescriptionLengthError {
            get {
                return ResourceManager.GetString("DescriptionLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email can&apos;t be empty.
        /// </summary>
        public static string EmailEmptyError {
            get {
                return ResourceManager.GetString("EmailEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce a valid email.
        /// </summary>
        public static string EmailInvalidError {
            get {
                return ResourceManager.GetString("EmailInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email must have between 1 and 75 characters.
        /// </summary>
        public static string EmailLengthError {
            get {
                return ResourceManager.GetString("EmailLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name can&apos;t be empty.
        /// </summary>
        public static string LastNameEmptyError {
            get {
                return ResourceManager.GetString("LastNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name must have between 1 and 50 characters.
        /// </summary>
        public static string LastNameLengthError {
            get {
                return ResourceManager.GetString("LastNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name can&apos;t be empty.
        /// </summary>
        public static string NameEmptyError {
            get {
                return ResourceManager.GetString("NameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name must have between 1 and 50 characters.
        /// </summary>
        public static string NameLengthError {
            get {
                return ResourceManager.GetString("NameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password can&apos;t be empty.
        /// </summary>
        public static string NewPasswordEmptyError {
            get {
                return ResourceManager.GetString("NewPasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password must have between 1 and 50 characters.
        /// </summary>
        public static string NewPasswordLengthError {
            get {
                return ResourceManager.GetString("NewPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old password can&apos;t be empty.
        /// </summary>
        public static string OldPasswordEmptyError {
            get {
                return ResourceManager.GetString("OldPasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old password must have between 1 and 50 characters.
        /// </summary>
        public static string OldPasswordLengthError {
            get {
                return ResourceManager.GetString("OldPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password can&apos;t be empty.
        /// </summary>
        public static string PasswordEmptyError {
            get {
                return ResourceManager.GetString("PasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must have between 1 and 50 characters.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select an image.
        /// </summary>
        public static string PictureNonSelectedError {
            get {
                return ResourceManager.GetString("PictureNonSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username can&apos;t be empty.
        /// </summary>
        public static string UserNameEmptyError {
            get {
                return ResourceManager.GetString("UserNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username must have between 1 and 50 characters.
        /// </summary>
        public static string UserNameLengthError {
            get {
                return ResourceManager.GetString("UserNameLengthError", resourceCulture);
            }
        }
    }
}
